ProjectNet/ProjectNet/Controllers/SelectBooksController.cs
using ProjectNet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectNet.Controllers
{
    public class SelectBooksController : Controller
    {
        // GET: SelectBooks

        datamvcDataContext db = new datamvcDataContext();

        public ActionResult Index()
        {
            List<Book> model = db.Books.ToList();

            return View(model);
        }

        public ActionResult OrderByTitle()
        {
            var book = from p in db.Books
                       orderby p.Tytuł ascending
                       select p;
            return View(book);
        }

        public ActionResult OrderByDate()
        {
            var book = from p in db.Books
                       orderby p.Data_wydania ascending
                       select p;
            return View(book);
        }
    }
}

ProjectNet/ProjectNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Books Browser", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Przeglądaj książki", "Index", "SelectBooks")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Krystian Graj</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>